---
language: python
services: docker

env:
  global:
    - ROLE_NAME: vim-extensions
  matrix:
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies
  - pip install molecule docker

before_script:
  # Use the actual Ansible Galaxy role name for the project directory
  - cd ../
  - cd $ROLE_NAME

script:
  # Run tests
  - molecule test -s jobs

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications
