---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: vim_extensions_ubuntu1804
    image: ubuntu:18.04
  - name: vim_extensions_ubuntu1604
    image: ubuntu:16.04
  - name: vim_extensions_ubuntu1404
    image: ubuntu:14.04
  - name: vim_extensions_centos7
    image: centos:7
  - name: vim_extensions_centos6
    image: centos:6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
