---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: vim_extensions_ubuntu2004
    image: ubuntu:20.04
  - name: vim_extensions_ubuntu1804
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: vim_extensions_ubuntu1604
    image: "geerlingguy/docker-ubuntu1604-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: vim_extensions_centos8
    image: "geerlingguy/docker-centos8-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: vim_extensions_centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: vim_extensions_debianstretch
    image: "geerlingguy/docker-debian9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: vim_extensions_debianbuster
    image: "geerlingguy/docker-debian10-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      vim_extensions_centos8:
        ansible_python_interpreter: /usr/bin/python3
      vim_extensions_ubuntu1804:
        ansible_python_interpreter: /usr/bin/python3
      vim_extensions_debianbuster:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
